apiVersion: apps/v1
kind: Deployment
metadata:
  name: boinc-deployment
  labels:
    app: boinc
spec:
  replicas: 10
  selector:
    matchLabels:
      app: boinc
  template:
    metadata:
      labels:
        app: boinc
    spec:
      containers:
      - name: boinc
        image: ghcr.io/linuxserver/boinc                    # x86-64	latest
        #image: ghcr.io/linuxserver/boinc:arm64v8-latest    # arm64	arm64v8-latest
        #image: ghcr.io/linuxserver/boinc:arm32v7-latest    # armhf	arm32v7-latest
        env:
        - name: BOINC_CMD_LINE_OPTIONS
          value: "--acct_mgr attach https://scienceunited.org/ $SECRET_USERNAME $SECRET_PASSWORD"
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: manager-credentials
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: manager-credentials
              key: password
